VOO4-2344 Add regex statut to JsFunctionsScanner
Epiconcept-Paris/Gettext pull request #1
Opened 2023-10-10 15:22 UTC by mdurand86

2023-10-12 09:47 UTC, epi-JRD requested changes

2023-10-12 09:47 UTC, epi-JRD commented on src/Utils/JsFunctionsScanner.php
> +                            if ( !is_numeric( $prev ) ) {
si je comprend bien, tu considères qu'une regexp ne peut pas inclure de chiffre alors qu'on peut très bien avoir ça /ma_regrexp12345/, non ?

2023-10-12 09:47 UTC, epi-JRD commented on src/Utils/JsFunctionsScanner.php
> +                            if ( !is_numeric( $prev ) ) {
en fait, c'est plus `if($prev !== '\')`

2023-10-12 09:47 UTC, epi-JRD commented on src/Utils/JsFunctionsScanner.php
> +                            if ( $next == ';' || $next == ',' || $next == ' ' ) {
on peut aussi avoir un retour à la ligne

2023-10-13 08:17 UTC, epi-JRD commented on src/Utils/JsFunctionsScanner.php
> +                            if ( $prev !== '\\' ) {
pourquoi 2 backslashes?

2023-10-13 08:41 UTC, mdurand86 commented on src/Utils/JsFunctionsScanner.php
> +                            if ( $next == ';' || $next == ',' || $next == ' ' ) {
En fait, c'est une erreur de ma part, ce if n'est pas nécessaire. C'est un premier test que j'avais fait avant que l'on en parle et que l'on décide de créer un statut regex

2023-10-13 08:41 UTC, mdurand86 commented on src/Utils/JsFunctionsScanner.php
> +                            if ( !is_numeric( $prev ) ) {
Exact, tu as raison, je vais changer ça. Mais je pense que c'est une protection qui n'est pas nécessaire. Quand on rencontre un \ on saute automatiquement  le caractère d'après : https://github.com/Epiconcept-Paris/Gettext/blob/30c37112642c52984f84410b4c37f2553c3d4bef/src/Utils/JsFunctionsScanner.php#L39L64

2023-10-13 08:41 UTC, mdurand86 commented on src/Utils/JsFunctionsScanner.php
> +                            if ( $prev !== '\\' ) {
Le premier sert à échapper le deuxième. Sinon il échapperait la quote et le reste du code de la page serait compris comme une chaine de caractère.

2023-10-13 08:41 UTC, epi-JRD approved these changes

2023-10-25 08:33 UTC, merged